steps:
  # 建置映像檔
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - .

  # 推送映像檔到 Container Registry / Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

  # 部署到 Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - "--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
